; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Feb 21 2021 15:00:32 GMT-0600 (Central Standard Time)
M280 P0 S10 ; deploy BLTouch

