; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Feb 21 2021 15:00:32 GMT-0600 (Central Standard Time)
M280 P0 S90 ; retract BLTouch
M300 S440 P500

