; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Feb 21 2021 15:00:33 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

